const data = {
  products: [
    {
      name: 'French Bread',
      slug: 'French-Bread',
      brand: 'my Bakery',
      category: 'Bakery',
      image: '/images/bread.jfif',
      rating: 4.5,
      reviews: 10,
      stock: 30,
      price: 2.0,
      currency: 'EUR',
    },
    {
      name: ' packaged fresh chicken',
      slug: 'packaged-fresh-chicken',
      brand: 'the tasty chicken',
      category: 'farm',
      image: '/images/chicken.jfif',
      rating: 4.4,
      reviews: 8,
      stock: 10,
      price: 1.5,
      currency: 'EUR',
    },
    {
      name: 'bottled milk',
      slug: 'bottled-milk',
      brand: 'milky',
      category: 'dairy',
      image: '/images/milk_bottle.jfif',
      rating: 4.6,
      reviews: 15,
      stock: 15,
      price: 2.5,
      currency: 'EUR',
    },
    {
      name: 'orange juice',
      slug: 'orange-juice',
      brand: 'funny orange',
      category: 'juice',
      image: '/images/orange_juice.jfif',
      rating: 4.6,
      reviews: 5,
      stock: 11,
      price: 1.2,
      currency: 'EUR',
    },
    {
      name: 'red wine',
      slug: 'red-wine',
      brand: 'elixir',
      category: 'wine',
      image: '/images/wine.jfif',
      rating: 4.4,
      reviews: 8,
      stock: 20,
      price: 4.0,
      currency: 'EUR',
    },
  ],
};

export default data;
